apiVersion: v1
kind: Service
metadata:
  labels:
    app: promtail
  name: promtail
  namespace: default
spec:
  ports:
  - port: 9080
    protocol: TCP
    targetPort: 9080
  selector:
    app: promtail
  type: NodePort
